language: python
sudo: required
dist: trusty
python:
    - '3.5'

before_install:
    - sudo apt update && sudo apt install -y inkscape

install:
    - pip install -r requirements_dev.txt
env:
    - TOX_ENV=lint
    - TOX_ENV=py27,stats
    - TOX_ENV=py35,stats
    - TOX_ENV=doc

script:
  - tox -c tox.ini -e $TOX_ENV
  # this is already in tox
  # - coverage run --source=dhcpcanon setup.py test

after_success:
  - coveralls
  - codecov
