language: python
sudo: required
dist: trusty
python:
    - '3.5'

before_install:
    - sudo apt update && sudo apt install -y inkscape libdbus-glib-1-dev
    # - echo "Python diagnostic Information"
    # - env
    # - sudo dpkg -l|grep python|grep dev
    # - 'which -a python'
    # - python --version
    # - python-config --includes
    # - ls -l ~/virtualenv

install:
    - pip install -r requirements_dev.txt

env:
  global:
    # The dbus-python maintainer hit these bugs on travis, see his comments on the
    # travis bug report: https://github.com/travis-ci/travis-ci/issues/6530
    # See https://github.com/mitya57/secretstorage/blob/2636a47b45aff51a21dfaf1cbd9f1f3c1347f7f4/.travis.yml for an example workaround
    # This is also a known issue and filed on the python bugtracker: https://bugs.python.org/issue7352
    - 'PYTHON_LIBS="-L$(python-config --prefix)/lib $(python-config --libs)"'
    - PY_ENABLE_SHARD=0
    - TOX_ENV=lint
    - TOX_ENV=py35,stats
    - TOX_ENV=doc

script:
  - tox -c tox.ini -e $TOX_ENV
  # this is already in tox
  # - coverage run --source=dhcpcanon setup.py test

after_success:
  - coveralls
  - codecov
