#!/bin/sh
set -e
case $1 in
    configure)
    if ! getent passwd dhcpcanon >/dev/null ; then
        echo "adding dhcpcanon user..."
        adduser --quiet --system --no-create-home --group \
        --home "/run/dhcpcanon" \
        --gecos 'dhcpcanon system user,,,' \
        dhcpcanon
    fi
    if getent group resolvconf-admins >/dev/null; then
        adduser --quiet dhcpcanon resolvconf-admins
    fi
    ;;
esac

#DEBHELPER#

exit 0
